#!/bin/bash
# bootstrap/generators/boundaries.sh — Auto-generate .context/boundaries.yml
#
# API: generate TARGET REGISTRY
#   TARGET — project root directory
#   REGISTRY — path to registry.yaml
#
# Classes follow core/contracts/consumer/boundaries.yaml: pristine (never edited),
# editable, generated, secret. Paths are relative to the project root.

generate() {
  local target_dir="$1" registry="$2"

  mkdir -p "${target_dir}/.context"

  if [ -s "${target_dir}/.context/boundaries.yml" ]; then
    echo "  → .context/boundaries.yml already exists, skipping."
    return
  fi

  local generated_paths=""

  # Auto-detect generated paths from .gitignore
  if [ -f "${target_dir}/.gitignore" ]; then
    while IFS= read -r line; do
      line=$(echo "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
      [[ -z "$line" || "$line" == \#* || "$line" == "!"* ]] && continue
      generated_paths="${generated_paths}    - path: \"${line}\"\n      reason: \"ignored by git\"\n"
    done < "${target_dir}/.gitignore"
  fi

  # Always-include generated paths
  local always_generated=("node_modules" "dist" "build" ".next" "coverage")
  for p in "${always_generated[@]}"; do
    if ! echo -e "$generated_paths" | grep -qF "path: ${p}"; then
      generated_paths="${generated_paths}    - path: ${p}\n      reason: \"build output\"\n"
    fi
  done

  cat > "${target_dir}/.context/boundaries.yml" << HEREDOC
# Boundaries — where an agent may write
# Generated by Underboss bootstrap. Paths are relative to the project root.

boundaries:
  pristine:
    - path: docs/.control/
      reason: "Underboss submodule (managed by git submodule update --remote)"

  editable:
    - path: docs/
      reason: "project documentation (except docs/.control/)"
    - path: src/
      reason: "application source code"
    - path: tests/
      reason: "tests"

  generated:
    - path: .context/project.yml
      reason: "agent entry metadata (generated by bootstrap, user fills in)"
    - path: .context/boundaries.yml
      reason: "boundary definitions (generated by bootstrap, user adjusts)"
    - path: .context/agent-entry.md
      reason: "agent entry protocol (generated by bootstrap)"
    - path: CLAUDE.md
      reason: "Underboss snippet (prepended by bootstrap)"
    - path: .github/workflows/docs-validate.yml
      reason: "CI workflow (created by bootstrap)"
$(echo -e "$generated_paths")

  secret:
    - path: .env
      reason: "environment variables (never commit)"
    - path: ".env.*"
      reason: "environment variables (never commit)"
    - path: "*.key"
      reason: "private keys"
    - path: "*.pem"
      reason: "private keys"
    - path: secrets/
      reason: "secret configuration (never commit)"
HEREDOC

  echo "  → .context/boundaries.yml created."
}
